changelogprefix: '&b[Implicite]'
reloadmessage: 'Sikeresen ujratoltve!]'
noperm: '&c[Imp] Nincs jogod ehhez a parancshoz!'
changelogsor1: '&c - Új kitek 5 potival.'
changelogsor2: '&c - Duel rendszer'
changelogsor3: '&c - Regen effect esetén dara'
changelogsor4: '&c - Új anticheat!'
changelogsor5: '&c - OP aranyalmák csökkentve lettek, több esély a kezdőnek!'
changelogsor6: 'asdasd'
changelogsor7: 'asdasd'
changelogsor8: 'asdasd'
changelogsor9: 'asdasd'